package com.mineclawd.buildin.kubejsoffline;

import dev.architectury.platform.Platform;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * KubeJSOffline Integration for KubeJS scripts
 * Provides concise KubeJS knowledge base access from JavaScript
 */
public final class KubeJSOfflineIntegration {
    private static final Logger LOGGER = LogManager.getLogger();
    
    private KubeJSOfflineIntegration() {
    }
    
    /**
     * Generate concise KubeJS knowledge base from KubeJSOffline documentation
     * This method is called from KubeJS scripts to fetch documentation
     */
    public static String generateConciseKubeJSKnowledge() {
        if (!KubeJSOfflineToolExecutor.isKubeJSOfflineAvailable()) {
            return "ERROR: KubeJSOffline mod is not installed.";
        }
        
        if (!KubeJSOfflineToolExecutor.isDocumentationGenerated()) {
            return "ERROR: KubeJSOffline documentation not generated. Please run: /kubejs offline_docs generate";
        }
        
        try {
            Path docsDir = Platform.getGameFolder().resolve("kubejs/documentation");
            
            StringBuilder knowledgeBase = new StringBuilder();
            knowledgeBase.append("# KubeJS Offline Knowledge Base (Generated by MineClawd)\n\n");
            
            List<Path> htmlFiles = Files.walk(docsDir)
                .filter(Files::isRegularFile)
                .filter(path -> path.toString().endsWith(".html"))
                .collect(Collectors.toList());
            
            knowledgeBase.append("## Documentation Statistics\n");
            knowledgeBase.append("- Total Documentation Files: ").append(htmlFiles.size()).append("\n\n");
            
            knowledgeBase.append("## Available Classes and Events\n\n");
            
            for (Path file : htmlFiles) {
                String fileName = file.getFileName().toString();
                if (fileName.contains("Event")) {
                    knowledgeBase.append("- Event: ").append(fileName.replace(".html", "")).append("\n");
                } else if (fileName.contains("class") || fileName.contains("index")) {
                    knowledgeBase.append("- Class: ").append(fileName.replace(".html", "")).append("\n");
                }
            }
            
            knowledgeBase.append("\n## Usage\n");
            knowledgeBase.append("Use `kubejsoffline-query-class` and `kubejsoffline-query-event` tools to query specific information.\n");
            
            LOGGER.info("[KubeJSOfflineIntegration] Generated concise knowledge base with {} files", htmlFiles.size());
            return knowledgeBase.toString();
            
        } catch (IOException e) {
            LOGGER.error("[KubeJSOfflineIntegration] Failed to generate knowledge base", e);
            return "ERROR: Failed to generate knowledge base: " + e.getMessage();
        }
    }
}